version: '3.4'

services:
  coinclipper.btcwalletservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    image: ${DOCKER_REGISTRY}coinclipper.btcwallet
    build:
      context: .
      dockerfile: dotnet/core31/CoinClipper.BtcWallet/Dockerfile
    ports:
      - "8082:5000" 
